#ifndef H_SETTINGS_H
#define H_SETTINGS_H

typedef enum LoadSettingsResult {
  LOAD_SETTINGS_SUCCESS = 0,
  LOAD_SETTINGS_ERROR_FILE_NOT_FOUND,
  LOAD_SETTINGS_ERROR_EMPTY_FILE,
  LOAD_SETTINGS_ERROR_FILE_READ_FAILURE,
  LOAD_SETTINGS_ERROR_INVALID_FORMAT,
  LOAD_SETTINGS_ERROR_START_MAGIC,
  LOAD_SETTINGS_ERROR_VERSION_MISMATCH,
} LoadSettingsResult;

LoadSettingsResult loadSettingsFromDSF(const char* filename);

#endif
